name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.3'
    - run: flutter pub get
    - run: flutter build apk
    - name: Upload apk artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: build/app/outputs/apk/release/app-release.apk
